language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install python-coveralls"
  - "pip install coverage"       # Add me to install coverage.py
  - "pip install nose"           # Add me to install nose
#  - "pip install coveralls"
# command to run tests
script:
  - "nosetests --with-coverage"
#  - "nosetests --with-coverage --cover-erase --cover-package=gorinich/ --cover-html"
after_success:
  - "coveralls"
