language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
#  - "pip install -e ."
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install nose"
#  - "pip install coveralls"
script:
  - "python setup.py install"
  - "nosetests --with-coverage"
#  - "nosetests --with-coverage --cover-package=gorinich/"
after_success:
  - "coveralls"
