language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
install:
  - "pip install -e ."
#  - "pip install python-coveralls"
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install nose"
script:
  - "nosetests --with-coverage --cover-package=gorinich"
  - "coverage run --source=. setup.py test"
after_success:
  - "coveralls"
notifications:
    email:
        recipients:
            - "taras@drapalyuk.com"
        on_success: "always"
        on_failure: "always"
